spring:
  jpa:
    show-sql: ${SHOW_SQL:false}
    generate-ddl: false
    database: postgresql
  datasource:
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}