CREATE TABLE IF NOT EXISTS TASK
(
    ID                BIGINT                      NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOME              CHARACTER VARYING(100)      NOT NULL,
    INCLUSAO_USUARIO  CHARACTER VARYING(50)       NOT NULL,
    INCLUSAO_DATA     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ALTERACAO_USUARIO CHARACTER VARYING(50),
    ALTERACAO_DATA    TIMESTAMP WITHOUT TIME ZONE
);